steps:
  # Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/sit323-737-2023-t1-prac5p:$COMMIT_SHA",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/sit323-737-2023-t1-prac5p:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/mydeployment",
        "mynode=gcr.io/sit323-23t1-kincaid-24df7e9/sit323-737-2023-t1-prac5p:$COMMIT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=australia-southeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=user-cluster"
